- src/utils/helpers.test.ts
> fix: fixing build

- Dockerfile
This PR fixes some issues on the dockerfile
> fix: minor fixes to dockerfile

- Dockerfile
> fix: remove reference to yarn folder

- src/routes.ts
> fix: removing duplicated route

- src/index.ts
Changed Host Port to Container port
Host port differ from container port causing restarts
> chore: changed host port

- Dockerfile
- Remove reference for global installation of PM2
> fix: remove reference to install pm2 on dockerfile

- .github/workflows/deploy_testnet.yml
- .github/workflows/deploy_testnet_api.yml
- Dockerfile
- api/Dockerfile
Explorer-api testnet deployment pipeline
> Explorer api

- Dockerfile
- Dockerfile.api
- yarn.lock
install git and use v1 of yarn
> fix: fix dockerfile

- src/indexer/healthcheck.ts
- src/indexer/index.ts
> chore: add healthcheck route

- .github/workflows/deploy_testnet.yml
Add db username and password to indexer deployment.
> fix: update indexer deployment action

- .github/workflows/deploy_mainnet.yml
- .github/workflows/deploy_mainnet_api.yml
Mainnet Pipelines for Explorer Indexer and API
> pipelines: explorer

- .github/workflows/deploy_mainnet.yml
- .github/workflows/deploy_mainnet_api.yml
> fix: add aws env variable to deployment action

- .github/workflows/deploy_mainnet.yml
- .github/workflows/deploy_mainnet_api.yml
> image tags

- .github/workflows/deploy_mainnet.yml
- .github/workflows/deploy_mainnet_api.yml
- .github/workflows/deploy_testnet.yml
- .github/workflows/deploy_testnet_api.yml
> naming: diff pipelines

- docker-compose.yml
- prisma/schema.prisma
- src/Interfaces/TransfersInterfaces/index.ts
- src/indexer/repository/transfer.ts
- src/indexer/utils/evm/index.ts
- src/indexer/utils/substrate/index.ts
- src/services/transfers.service.test.ts
- src/services/transfers.service.ts
- src/utils/helpers.ts
Fix substrate indexing logic that creates multiple records on update.
> fix: fix double created records

- src/indexer/repository/transfer.ts
> fix: convert from domain id to int

- src/indexer/services/substrateIndexer/substrateTypes.ts
- src/indexer/utils/substrate/index.ts
store correct extrinsic id
store correct extrinsic id
Closes: #78 
manually
> fix: store correct extrinsic id

- src/indexer/repository/transfer.ts
- src/indexer/utils/substrate/index.ts
insert destination for deposit event
insert destination for deposit event
Closes: #81 
manually
> fix: insert destination for deposit event

- src/indexer/index.ts
- src/indexer/services/coinmarketcap/coinmarketcap.service.ts
- Changes on they way coinmarketcap service is instantiated for release
- Homologates with whats present in PR #96 
> chore: changes on instantiation of coinmarketcap service

- src/indexer/utils/substrate/index.ts
remove commas from the feeAmount
Closes: #108
> fix: remove commas from the feeAmount

- .github/workflows/deploy_mainnet.yml
deploy v2 of sygma explorer-indexer
> chore: sygma explorer-indexer v2

- .github/workflows/deploy_mainnet.yml
> chore: disable v2 deployment

- .github/workflows/ci.yaml
- license-config.json
Added license checking to workflow so the newly created files have to have it defined.
> fix: Added license checking to workflow

- src/indexer/services/coinmarketcap/coinmarketcap.service.ts
Added more logs to CoinMarketCap service for easier debugging.
> fix: Added more logs to CoinMarketCap service

- src/indexer/config/index.ts
- src/indexer/utils/evm/index.ts
- tests/e2e/domainAndResourceRoute.spec.ts
- tests/e2e/indexing.spec.ts
- tests/e2e/resourceRoute.spec.ts
- tests/unit/parseLogs.spec.ts
parse recipient for GMP transfer
parse recipient for GMP transfer
Closes: #105 
manually
> fix: parse recipient for GMP transfer

- src/Interfaces/TransfersInterfaces/index.ts
- src/controllers/TransfersController.ts
- src/controllers/schemas.ts
- src/routes.ts
- src/services/transfers.service.ts
- tests/e2e/indexing.spec.ts
Updated endpoint to search by txHash and domain ID. Also, updated affected tests and added schema for the mentioned route. 
closes #115
> fix: Updating endpoint to search by txHash and domain ID

- package.json
copy .ejs files into build
copy .ejs files that are used to construct message that is sent to was sns into build folder
> fix: copy .ejs files into build

- src/indexer/utils/substrate/index.ts
- tests/e2e/indexing.spec.ts
store default fee for substrate
This is a fix for indexing transfers from old version of the pallet that don't emit feeCollected event
> fix: store default fee for substrate

- .github/workflows/deploy_mainnet.yml
> chore: uncomment deploy_v2

- src/services/transfers.service.ts
fix: return distinct values
This is just a quick fix. there is some issue with sorting that returns duplicate values
> fix: return distinct values

- src/services/transfers.service.ts
This was a hot fix for issue with duplicate values. This is now fixed by #149 
> chore: revert distinct

- Dockerfile
- license-config.json
- start-prod.sh
Fix db schema
We need to run `prisma db push` command to apply indexes from schema to database.
Closes: #131 
locally
> fix: push indexes to database

- src/indexer/services/evmIndexer/evmIndexer.ts
- src/indexer/services/substrateIndexer/substrateIndexer.ts
Add reorg count
Add reorg count so that when reorgs happen we index blocks correctly
Closes: #165
> fix: add reorg count

- src/indexer/repository/execution.ts
- src/indexer/repository/transfer.ts
- src/indexer/services/evmIndexer/evmIndexer.ts
- src/indexer/utils/evm/index.ts
- src/indexer/utils/substrate/index.ts
fix handling multiple failedExecution events
Error happened when there was multiple failedExecution events with the same depositNonce
Closes: #171 
Manually/e2e tests
> fix: handling multiple failedExecution events

- .github/workflows/deploy_testnet.yml
- .github/workflows/deploy_testnet_api.yml
> fix: add awsEnv

- src/indexer/repository/resource.ts
update decimals if the resource already exists
> fix: update decimals

- src/routes/routes.mainnet.ts
- src/routes/routes.testnet.ts
fix substrate -> evm routes
fix substrate -> evm routes
> fix: fix substrate -> evm routes

- src/indexer/services/monitoringService/index.ts
- src/indexer/services/monitoringService/warningTemplate.ejs
add environment to pending transfers monitoring message
> chore: add environment to pending transfers monitoring message

- .github/workflows/deploy_mainnet.yml
> chore: comment out v2 deployment

- .github/workflows/deploy_mainnet.yml
Remove stable Tag to avoid deploying stable tags to Mainnet
> chore: removed image stable tag

- .github/workflows/deploy_mainnet.yml
- .github/workflows/deploy_testnet.yml
- src/utils/logger.ts
Add version to log context
Closes: #190
> chore: add version to log context

- prisma/schema.prisma
- src/indexer/services/evmIndexer/evmTypes.ts
- src/indexer/utils/evm/index.ts
- src/indexer/utils/substrate/index.ts
- src/interfaces/TransfersInterfaces/index.ts
- src/utils/helpers.ts
- tests/e2e/domainAndResourceRoute.spec.ts
- tests/e2e/indexing.spec.ts
- tests/e2e/resourceRoute.spec.ts
store correct fee decimals value
remove resource from fee collection
add decimals to fee collection
update API
update e2e tests
Closes: #193 
@wainola could you please update explorer-ui so it uses new, updated API response. [here](https://app.zenhub.com/workspaces/sygma-protocol-62f126a54b7d5a55203732f0/issues/gh/sygmaprotocol/explorer-ui/169) is task wit more information
e2e tests
> fix: store correct fee decimals value

- .github/workflows/deploy_mainnet_api.yml
- .github/workflows/deploy_testnet.yml
- .github/workflows/deploy_testnet_api.yml
- src/controllers/schemas.ts
> chore: use version for image tag

- src/indexer/utils/evm/index.ts
> fix: fix typo

- src/routes/routes.testnet.ts
Fix type of nonfungible resource on domain 5.
> fix: type for non-fungible resource on domain 5

- src/indexer/services/evmIndexer/evmTypes.ts
- src/indexer/utils/evm/index.ts
handle semifungible transfers
handle semifungible transfers
Closes: #185
> feat: handle semifungible transfers

- src/routes/routes.testnet.ts
> chore: add layer-edge route

- src/routes/routes.testnet.ts
> chore: remove phala

- src/utils/domainMetadata.ts
- src/utils/resourcesMetadata.ts
> fix: add missing metadata

- src/indexer/utils/evm/index.ts
Handle unknown error messages
Handle error messages that are not known and a result of contract revert function
> fix: handle unknown error messages

- src/utils/resourcesMetadata.ts
> feat: updated metadata with usdc

- src/utils/resourcesMetadata.ts
> fix: symbol name

- .github/workflows/deploy_testnet.yml
- .github/workflows/deploy_testnet_api.yml
> chore: fixed env name

- .github/workflows/deploy_mainnet_api.yml
> chore: fix script format

- Dockerfile
- Dockerfile.api
> fix: set node version

- docker-compose.yml
- src/indexer/repository/transfer.ts
- src/indexer/utils/evm/index.ts
- src/indexer/utils/substrate/index.ts
- tests/e2e/domainAndResourceRoute.spec.ts
- tests/e2e/domainRoute.spec.ts
- tests/e2e/indexing.spec.ts
- tests/e2e/resourceRoute.spec.ts
- tests/e2e/sourceToDestDomainRoute.spec.ts
- if failedExecution comes after the transfer is successfully executed, just ignore that event
- added edge case fix - always upsert deposit, if updating transfer, don't update the status
> fix: fix tests and ignore failed transfers if already executed

- src/routes/routes.mainnet.ts
- src/utils/domainMetadata.ts
> chore: remove khala routes and metadata
